//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.42000 によって自動生成されました。
// 
#pragma warning disable 1591

namespace is2WakeUpDBCon.is2EXDBGET {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://Walkthrough/XmlWebServices/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EX_AM11GETOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM07GETOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM10GETOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM11GETOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM12GETOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM13GETSOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM14GETSOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM15GETOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM17GETOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM18GETOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_CM19GETOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_XM01_GetUpdDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_XM01_SetUpdDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback EX_SM01SETOperationCompleted;
        
        private System.Threading.SendOrPostCallback wakeupDBOperationCompleted;
        
        private System.Threading.SendOrPostCallback wakeupDB2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://wwwis2.fukutsu.co.jp/is2ex/is2EXDBGET/Service1.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EX_AM11GETCompletedEventHandler EX_AM11GETCompleted;
        
        /// <remarks/>
        public event EX_CM07GETCompletedEventHandler EX_CM07GETCompleted;
        
        /// <remarks/>
        public event EX_CM10GETCompletedEventHandler EX_CM10GETCompleted;
        
        /// <remarks/>
        public event EX_CM11GETCompletedEventHandler EX_CM11GETCompleted;
        
        /// <remarks/>
        public event EX_CM12GETCompletedEventHandler EX_CM12GETCompleted;
        
        /// <remarks/>
        public event EX_CM13GETSCompletedEventHandler EX_CM13GETSCompleted;
        
        /// <remarks/>
        public event EX_CM14GETSCompletedEventHandler EX_CM14GETSCompleted;
        
        /// <remarks/>
        public event EX_CM15GETCompletedEventHandler EX_CM15GETCompleted;
        
        /// <remarks/>
        public event EX_CM17GETCompletedEventHandler EX_CM17GETCompleted;
        
        /// <remarks/>
        public event EX_CM18GETCompletedEventHandler EX_CM18GETCompleted;
        
        /// <remarks/>
        public event EX_CM19GETCompletedEventHandler EX_CM19GETCompleted;
        
        /// <remarks/>
        public event EX_XM01_GetUpdDateCompletedEventHandler EX_XM01_GetUpdDateCompleted;
        
        /// <remarks/>
        public event EX_XM01_SetUpdDateCompletedEventHandler EX_XM01_SetUpdDateCompleted;
        
        /// <remarks/>
        public event EX_SM01SETCompletedEventHandler EX_SM01SETCompleted;
        
        /// <remarks/>
        public event wakeupDBCompletedEventHandler wakeupDBCompleted;
        
        /// <remarks/>
        public event wakeupDB2CompletedEventHandler wakeupDB2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_AM11GET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_AM11GET(string[] sUser) {
            object[] results = this.Invoke("EX_AM11GET", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_AM11GET(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_AM11GET", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_AM11GET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_AM11GETAsync(string[] sUser) {
            this.EX_AM11GETAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_AM11GETAsync(string[] sUser, object userState) {
            if ((this.EX_AM11GETOperationCompleted == null)) {
                this.EX_AM11GETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_AM11GETOperationCompleted);
            }
            this.InvokeAsync("EX_AM11GET", new object[] {
                        sUser}, this.EX_AM11GETOperationCompleted, userState);
        }
        
        private void OnEX_AM11GETOperationCompleted(object arg) {
            if ((this.EX_AM11GETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_AM11GETCompleted(this, new EX_AM11GETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM07GET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM07GET(string[] sUser) {
            object[] results = this.Invoke("EX_CM07GET", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM07GET(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM07GET", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM07GET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM07GETAsync(string[] sUser) {
            this.EX_CM07GETAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_CM07GETAsync(string[] sUser, object userState) {
            if ((this.EX_CM07GETOperationCompleted == null)) {
                this.EX_CM07GETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM07GETOperationCompleted);
            }
            this.InvokeAsync("EX_CM07GET", new object[] {
                        sUser}, this.EX_CM07GETOperationCompleted, userState);
        }
        
        private void OnEX_CM07GETOperationCompleted(object arg) {
            if ((this.EX_CM07GETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM07GETCompleted(this, new EX_CM07GETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM10GET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM10GET(string[] sUser) {
            object[] results = this.Invoke("EX_CM10GET", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM10GET(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM10GET", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM10GET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM10GETAsync(string[] sUser) {
            this.EX_CM10GETAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_CM10GETAsync(string[] sUser, object userState) {
            if ((this.EX_CM10GETOperationCompleted == null)) {
                this.EX_CM10GETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM10GETOperationCompleted);
            }
            this.InvokeAsync("EX_CM10GET", new object[] {
                        sUser}, this.EX_CM10GETOperationCompleted, userState);
        }
        
        private void OnEX_CM10GETOperationCompleted(object arg) {
            if ((this.EX_CM10GETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM10GETCompleted(this, new EX_CM10GETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM11GET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM11GET(string[] sUser) {
            object[] results = this.Invoke("EX_CM11GET", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM11GET(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM11GET", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM11GET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM11GETAsync(string[] sUser) {
            this.EX_CM11GETAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_CM11GETAsync(string[] sUser, object userState) {
            if ((this.EX_CM11GETOperationCompleted == null)) {
                this.EX_CM11GETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM11GETOperationCompleted);
            }
            this.InvokeAsync("EX_CM11GET", new object[] {
                        sUser}, this.EX_CM11GETOperationCompleted, userState);
        }
        
        private void OnEX_CM11GETOperationCompleted(object arg) {
            if ((this.EX_CM11GETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM11GETCompleted(this, new EX_CM11GETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM12GET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM12GET(string[] sUser) {
            object[] results = this.Invoke("EX_CM12GET", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM12GET(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM12GET", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM12GET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM12GETAsync(string[] sUser) {
            this.EX_CM12GETAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_CM12GETAsync(string[] sUser, object userState) {
            if ((this.EX_CM12GETOperationCompleted == null)) {
                this.EX_CM12GETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM12GETOperationCompleted);
            }
            this.InvokeAsync("EX_CM12GET", new object[] {
                        sUser}, this.EX_CM12GETOperationCompleted, userState);
        }
        
        private void OnEX_CM12GETOperationCompleted(object arg) {
            if ((this.EX_CM12GETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM12GETCompleted(this, new EX_CM12GETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM13GETS", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM13GETS(string[] sUser) {
            object[] results = this.Invoke("EX_CM13GETS", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM13GETS(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM13GETS", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM13GETS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM13GETSAsync(string[] sUser) {
            this.EX_CM13GETSAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_CM13GETSAsync(string[] sUser, object userState) {
            if ((this.EX_CM13GETSOperationCompleted == null)) {
                this.EX_CM13GETSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM13GETSOperationCompleted);
            }
            this.InvokeAsync("EX_CM13GETS", new object[] {
                        sUser}, this.EX_CM13GETSOperationCompleted, userState);
        }
        
        private void OnEX_CM13GETSOperationCompleted(object arg) {
            if ((this.EX_CM13GETSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM13GETSCompleted(this, new EX_CM13GETSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM14GETS", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM14GETS(string[] sUser) {
            object[] results = this.Invoke("EX_CM14GETS", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM14GETS(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM14GETS", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM14GETS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM14GETSAsync(string[] sUser) {
            this.EX_CM14GETSAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_CM14GETSAsync(string[] sUser, object userState) {
            if ((this.EX_CM14GETSOperationCompleted == null)) {
                this.EX_CM14GETSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM14GETSOperationCompleted);
            }
            this.InvokeAsync("EX_CM14GETS", new object[] {
                        sUser}, this.EX_CM14GETSOperationCompleted, userState);
        }
        
        private void OnEX_CM14GETSOperationCompleted(object arg) {
            if ((this.EX_CM14GETSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM14GETSCompleted(this, new EX_CM14GETSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM15GET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM15GET(string[] sUser) {
            object[] results = this.Invoke("EX_CM15GET", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM15GET(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM15GET", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM15GET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM15GETAsync(string[] sUser) {
            this.EX_CM15GETAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_CM15GETAsync(string[] sUser, object userState) {
            if ((this.EX_CM15GETOperationCompleted == null)) {
                this.EX_CM15GETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM15GETOperationCompleted);
            }
            this.InvokeAsync("EX_CM15GET", new object[] {
                        sUser}, this.EX_CM15GETOperationCompleted, userState);
        }
        
        private void OnEX_CM15GETOperationCompleted(object arg) {
            if ((this.EX_CM15GETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM15GETCompleted(this, new EX_CM15GETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM17GET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM17GET(string[] sUser, string[] s会員, string sZenUpdate) {
            object[] results = this.Invoke("EX_CM17GET", new object[] {
                        sUser,
                        s会員,
                        sZenUpdate});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM17GET(string[] sUser, string[] s会員, string sZenUpdate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM17GET", new object[] {
                        sUser,
                        s会員,
                        sZenUpdate}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM17GET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM17GETAsync(string[] sUser, string[] s会員, string sZenUpdate) {
            this.EX_CM17GETAsync(sUser, s会員, sZenUpdate, null);
        }
        
        /// <remarks/>
        public void EX_CM17GETAsync(string[] sUser, string[] s会員, string sZenUpdate, object userState) {
            if ((this.EX_CM17GETOperationCompleted == null)) {
                this.EX_CM17GETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM17GETOperationCompleted);
            }
            this.InvokeAsync("EX_CM17GET", new object[] {
                        sUser,
                        s会員,
                        sZenUpdate}, this.EX_CM17GETOperationCompleted, userState);
        }
        
        private void OnEX_CM17GETOperationCompleted(object arg) {
            if ((this.EX_CM17GETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM17GETCompleted(this, new EX_CM17GETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM18GET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM18GET(string[] sUser) {
            object[] results = this.Invoke("EX_CM18GET", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM18GET(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM18GET", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM18GET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM18GETAsync(string[] sUser) {
            this.EX_CM18GETAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_CM18GETAsync(string[] sUser, object userState) {
            if ((this.EX_CM18GETOperationCompleted == null)) {
                this.EX_CM18GETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM18GETOperationCompleted);
            }
            this.InvokeAsync("EX_CM18GET", new object[] {
                        sUser}, this.EX_CM18GETOperationCompleted, userState);
        }
        
        private void OnEX_CM18GETOperationCompleted(object arg) {
            if ((this.EX_CM18GETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM18GETCompleted(this, new EX_CM18GETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_CM19GET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_CM19GET(string[] sUser) {
            object[] results = this.Invoke("EX_CM19GET", new object[] {
                        sUser});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_CM19GET(string[] sUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_CM19GET", new object[] {
                        sUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_CM19GET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_CM19GETAsync(string[] sUser) {
            this.EX_CM19GETAsync(sUser, null);
        }
        
        /// <remarks/>
        public void EX_CM19GETAsync(string[] sUser, object userState) {
            if ((this.EX_CM19GETOperationCompleted == null)) {
                this.EX_CM19GETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_CM19GETOperationCompleted);
            }
            this.InvokeAsync("EX_CM19GET", new object[] {
                        sUser}, this.EX_CM19GETOperationCompleted, userState);
        }
        
        private void OnEX_CM19GETOperationCompleted(object arg) {
            if ((this.EX_CM19GETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_CM19GETCompleted(this, new EX_CM19GETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_XM01_GetUpdDate", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_XM01_GetUpdDate(string[] sUser, string sKaiinCD, string sTableKey) {
            object[] results = this.Invoke("EX_XM01_GetUpdDate", new object[] {
                        sUser,
                        sKaiinCD,
                        sTableKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_XM01_GetUpdDate(string[] sUser, string sKaiinCD, string sTableKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_XM01_GetUpdDate", new object[] {
                        sUser,
                        sKaiinCD,
                        sTableKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_XM01_GetUpdDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_XM01_GetUpdDateAsync(string[] sUser, string sKaiinCD, string sTableKey) {
            this.EX_XM01_GetUpdDateAsync(sUser, sKaiinCD, sTableKey, null);
        }
        
        /// <remarks/>
        public void EX_XM01_GetUpdDateAsync(string[] sUser, string sKaiinCD, string sTableKey, object userState) {
            if ((this.EX_XM01_GetUpdDateOperationCompleted == null)) {
                this.EX_XM01_GetUpdDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_XM01_GetUpdDateOperationCompleted);
            }
            this.InvokeAsync("EX_XM01_GetUpdDate", new object[] {
                        sUser,
                        sKaiinCD,
                        sTableKey}, this.EX_XM01_GetUpdDateOperationCompleted, userState);
        }
        
        private void OnEX_XM01_GetUpdDateOperationCompleted(object arg) {
            if ((this.EX_XM01_GetUpdDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_XM01_GetUpdDateCompleted(this, new EX_XM01_GetUpdDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_XM01_SetUpdDate", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_XM01_SetUpdDate(string[] sUser, string[] sKaiinCD, string sTableKey, string sUpdDate, string sUpdPG, string sUpdSya) {
            object[] results = this.Invoke("EX_XM01_SetUpdDate", new object[] {
                        sUser,
                        sKaiinCD,
                        sTableKey,
                        sUpdDate,
                        sUpdPG,
                        sUpdSya});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_XM01_SetUpdDate(string[] sUser, string[] sKaiinCD, string sTableKey, string sUpdDate, string sUpdPG, string sUpdSya, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_XM01_SetUpdDate", new object[] {
                        sUser,
                        sKaiinCD,
                        sTableKey,
                        sUpdDate,
                        sUpdPG,
                        sUpdSya}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_XM01_SetUpdDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_XM01_SetUpdDateAsync(string[] sUser, string[] sKaiinCD, string sTableKey, string sUpdDate, string sUpdPG, string sUpdSya) {
            this.EX_XM01_SetUpdDateAsync(sUser, sKaiinCD, sTableKey, sUpdDate, sUpdPG, sUpdSya, null);
        }
        
        /// <remarks/>
        public void EX_XM01_SetUpdDateAsync(string[] sUser, string[] sKaiinCD, string sTableKey, string sUpdDate, string sUpdPG, string sUpdSya, object userState) {
            if ((this.EX_XM01_SetUpdDateOperationCompleted == null)) {
                this.EX_XM01_SetUpdDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_XM01_SetUpdDateOperationCompleted);
            }
            this.InvokeAsync("EX_XM01_SetUpdDate", new object[] {
                        sUser,
                        sKaiinCD,
                        sTableKey,
                        sUpdDate,
                        sUpdPG,
                        sUpdSya}, this.EX_XM01_SetUpdDateOperationCompleted, userState);
        }
        
        private void OnEX_XM01_SetUpdDateOperationCompleted(object arg) {
            if ((this.EX_XM01_SetUpdDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_XM01_SetUpdDateCompleted(this, new EX_XM01_SetUpdDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/EX_SM01SET", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EX_SM01SET(string[] sUser, string[] sGetData) {
            object[] results = this.Invoke("EX_SM01SET", new object[] {
                        sUser,
                        sGetData});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEX_SM01SET(string[] sUser, string[] sGetData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EX_SM01SET", new object[] {
                        sUser,
                        sGetData}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndEX_SM01SET(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EX_SM01SETAsync(string[] sUser, string[] sGetData) {
            this.EX_SM01SETAsync(sUser, sGetData, null);
        }
        
        /// <remarks/>
        public void EX_SM01SETAsync(string[] sUser, string[] sGetData, object userState) {
            if ((this.EX_SM01SETOperationCompleted == null)) {
                this.EX_SM01SETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEX_SM01SETOperationCompleted);
            }
            this.InvokeAsync("EX_SM01SET", new object[] {
                        sUser,
                        sGetData}, this.EX_SM01SETOperationCompleted, userState);
        }
        
        private void OnEX_SM01SETOperationCompleted(object arg) {
            if ((this.EX_SM01SETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EX_SM01SETCompleted(this, new EX_SM01SETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/wakeupDB", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wakeupDB() {
            object[] results = this.Invoke("wakeupDB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwakeupDB(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wakeupDB", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwakeupDB(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wakeupDBAsync() {
            this.wakeupDBAsync(null);
        }
        
        /// <remarks/>
        public void wakeupDBAsync(object userState) {
            if ((this.wakeupDBOperationCompleted == null)) {
                this.wakeupDBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwakeupDBOperationCompleted);
            }
            this.InvokeAsync("wakeupDB", new object[0], this.wakeupDBOperationCompleted, userState);
        }
        
        private void OnwakeupDBOperationCompleted(object arg) {
            if ((this.wakeupDBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wakeupDBCompleted(this, new wakeupDBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/wakeupDB2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wakeupDB2(int iConCnt) {
            object[] results = this.Invoke("wakeupDB2", new object[] {
                        iConCnt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwakeupDB2(int iConCnt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wakeupDB2", new object[] {
                        iConCnt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwakeupDB2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wakeupDB2Async(int iConCnt) {
            this.wakeupDB2Async(iConCnt, null);
        }
        
        /// <remarks/>
        public void wakeupDB2Async(int iConCnt, object userState) {
            if ((this.wakeupDB2OperationCompleted == null)) {
                this.wakeupDB2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwakeupDB2OperationCompleted);
            }
            this.InvokeAsync("wakeupDB2", new object[] {
                        iConCnt}, this.wakeupDB2OperationCompleted, userState);
        }
        
        private void OnwakeupDB2OperationCompleted(object arg) {
            if ((this.wakeupDB2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wakeupDB2Completed(this, new wakeupDB2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_AM11GETCompletedEventHandler(object sender, EX_AM11GETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_AM11GETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_AM11GETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM07GETCompletedEventHandler(object sender, EX_CM07GETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM07GETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM07GETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM10GETCompletedEventHandler(object sender, EX_CM10GETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM10GETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM10GETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM11GETCompletedEventHandler(object sender, EX_CM11GETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM11GETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM11GETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM12GETCompletedEventHandler(object sender, EX_CM12GETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM12GETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM12GETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM13GETSCompletedEventHandler(object sender, EX_CM13GETSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM13GETSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM13GETSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM14GETSCompletedEventHandler(object sender, EX_CM14GETSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM14GETSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM14GETSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM15GETCompletedEventHandler(object sender, EX_CM15GETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM15GETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM15GETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM17GETCompletedEventHandler(object sender, EX_CM17GETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM17GETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM17GETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM18GETCompletedEventHandler(object sender, EX_CM18GETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM18GETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM18GETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_CM19GETCompletedEventHandler(object sender, EX_CM19GETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_CM19GETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_CM19GETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_XM01_GetUpdDateCompletedEventHandler(object sender, EX_XM01_GetUpdDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_XM01_GetUpdDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_XM01_GetUpdDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_XM01_SetUpdDateCompletedEventHandler(object sender, EX_XM01_SetUpdDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_XM01_SetUpdDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_XM01_SetUpdDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void EX_SM01SETCompletedEventHandler(object sender, EX_SM01SETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EX_SM01SETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EX_SM01SETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void wakeupDBCompletedEventHandler(object sender, wakeupDBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wakeupDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wakeupDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void wakeupDB2CompletedEventHandler(object sender, wakeupDB2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wakeupDB2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wakeupDB2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591