//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2443
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 1.1.4322.2443 によって自動生成されました。
// 
namespace is2WakeUpDBCon.is2syukka {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://Walkthrough/XmlWebServices/")]
    public class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://localhost/is2/is2syukka/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_syukka", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_syukka(string[] sUser, string sKCode, string sBCode, string sTCode, string sICode, int iSyuka, string sSday, string sEday, string sJyoutai) {
            object[] results = this.Invoke("Get_syukka", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sICode,
                        iSyuka,
                        sSday,
                        sEday,
                        sJyoutai});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_syukka(string[] sUser, string sKCode, string sBCode, string sTCode, string sICode, int iSyuka, string sSday, string sEday, string sJyoutai, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_syukka", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sICode,
                        iSyuka,
                        sSday,
                        sEday,
                        sJyoutai}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_syukka(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_Ssyukka", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_Ssyukka(string[] sUser, string sKCode, string sBCode, string sDay, int iJNo) {
            object[] results = this.Invoke("Get_Ssyukka", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sDay,
                        iJNo});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_Ssyukka(string[] sUser, string sKCode, string sBCode, string sDay, int iJNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_Ssyukka", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sDay,
                        iJNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_Ssyukka(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Ins_syukka", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Ins_syukka(string[] sUser, string[] sData) {
            object[] results = this.Invoke("Ins_syukka", new object[] {
                        sUser,
                        sData});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIns_syukka(string[] sUser, string[] sData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ins_syukka", new object[] {
                        sUser,
                        sData}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndIns_syukka(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_syukka", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Upd_syukka(string[] sUser, string[] sData) {
            object[] results = this.Invoke("Upd_syukka", new object[] {
                        sUser,
                        sData});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpd_syukka(string[] sUser, string[] sData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Upd_syukka", new object[] {
                        sUser,
                        sData}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndUpd_syukka(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Del_syukka", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Del_syukka(string[] sUser, string[] sData) {
            object[] results = this.Invoke("Del_syukka", new object[] {
                        sUser,
                        sData});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDel_syukka(string[] sUser, string[] sData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Del_syukka", new object[] {
                        sUser,
                        sData}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndDel_syukka(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Del_ikkatu", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Del_ikkatu(string[] sUser, string[] sData, string[] sInday, string[] sNo) {
            object[] results = this.Invoke("Del_ikkatu", new object[] {
                        sUser,
                        sData,
                        sInday,
                        sNo});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDel_ikkatu(string[] sUser, string[] sData, string[] sInday, string[] sNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Del_ikkatu", new object[] {
                        sUser,
                        sData,
                        sInday,
                        sNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndDel_ikkatu(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_tyakuten2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_tyakuten2(string[] sUser, string sYuubin) {
            object[] results = this.Invoke("Get_tyakuten2", new object[] {
                        sUser,
                        sYuubin});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_tyakuten2(string[] sUser, string sYuubin, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_tyakuten2", new object[] {
                        sUser,
                        sYuubin}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_tyakuten2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_hatuten2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_hatuten2(string[] sUser, string sKcode, string sBcode) {
            object[] results = this.Invoke("Get_hatuten2", new object[] {
                        sUser,
                        sKcode,
                        sBcode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_hatuten2(string[] sUser, string sKcode, string sBcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_hatuten2", new object[] {
                        sUser,
                        sKcode,
                        sBcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_hatuten2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_syuuyakuten2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_syuuyakuten2(string[] sUser, string sKcode, string sBcode) {
            object[] results = this.Invoke("Get_syuuyakuten2", new object[] {
                        sUser,
                        sKcode,
                        sBcode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_syuuyakuten2(string[] sUser, string sKcode, string sBcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_syuuyakuten2", new object[] {
                        sUser,
                        sKcode,
                        sBcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_syuuyakuten2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_csvwrite", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_csvwrite(string[] sUser, string sKCode, string sBCode, string sTCode, string sICode, int iSyuka, string sSday, string sEday, string sJyoutai) {
            object[] results = this.Invoke("Get_csvwrite", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sICode,
                        iSyuka,
                        sSday,
                        sEday,
                        sJyoutai});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_csvwrite(string[] sUser, string sKCode, string sBCode, string sTCode, string sICode, int iSyuka, string sSday, string sEday, string sJyoutai, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_csvwrite", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sICode,
                        iSyuka,
                        sSday,
                        sEday,
                        sJyoutai}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_csvwrite(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_csvwrite2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_csvwrite2(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_csvwrite2", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_csvwrite2(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_csvwrite2", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_csvwrite2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Ins_autoEntryData", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Ins_autoEntryData(string[] sUser, string[] sList) {
            object[] results = this.Invoke("Ins_autoEntryData", new object[] {
                        sUser,
                        sList});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIns_autoEntryData(string[] sUser, string[] sList, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ins_autoEntryData", new object[] {
                        sUser,
                        sList}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndIns_autoEntryData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_autoEntryPref", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_autoEntryPref(string[] sUser, string sYcode) {
            object[] results = this.Invoke("Get_autoEntryPref", new object[] {
                        sUser,
                        sYcode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_autoEntryPref(string[] sUser, string sYcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_autoEntryPref", new object[] {
                        sUser,
                        sYcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_autoEntryPref(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_autoEntryClaim", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_autoEntryClaim(string[] sUser, string sKcode, string sBcode, string sIcode) {
            object[] results = this.Invoke("Get_autoEntryClaim", new object[] {
                        sUser,
                        sKcode,
                        sBcode,
                        sIcode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_autoEntryClaim(string[] sUser, string sKcode, string sBcode, string sIcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_autoEntryClaim", new object[] {
                        sUser,
                        sKcode,
                        sBcode,
                        sIcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_autoEntryClaim(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Upd_syukkabi", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Upd_syukkabi(string[] sUser, string[] sData) {
            object[] results = this.Invoke("Upd_syukkabi", new object[] {
                        sUser,
                        sData});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpd_syukkabi(string[] sUser, string[] sData, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Upd_syukkabi", new object[] {
                        sUser,
                        sData}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndUpd_syukkabi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_syukka1", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_syukka1(string[] sUser, string sKCode, string sBCode, string sTCode, string sICode, int iSyuka, string sSday, string sEday, string sJyoutai) {
            object[] results = this.Invoke("Get_syukka1", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sICode,
                        iSyuka,
                        sSday,
                        sEday,
                        sJyoutai});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_syukka1(string[] sUser, string sKCode, string sBCode, string sTCode, string sICode, int iSyuka, string sSday, string sEday, string sJyoutai, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_syukka1", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sICode,
                        iSyuka,
                        sSday,
                        sEday,
                        sJyoutai}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_syukka1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_syukka2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_syukka2(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_syukka2", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_syukka2(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_syukka2", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_syukka2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_csvwrite1", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_csvwrite1(string[] sUser, string sKCode, string sBCode, string sTCode, string sICode, int iSyuka, string sSday, string sEday, string sJyoutai, string sIraiCd) {
            object[] results = this.Invoke("Get_csvwrite1", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sICode,
                        iSyuka,
                        sSday,
                        sEday,
                        sJyoutai,
                        sIraiCd});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_csvwrite1(string[] sUser, string sKCode, string sBCode, string sTCode, string sICode, int iSyuka, string sSday, string sEday, string sJyoutai, string sIraiCd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_csvwrite1", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sICode,
                        iSyuka,
                        sSday,
                        sEday,
                        sJyoutai,
                        sIraiCd}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_csvwrite1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Check_autoEntry1", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Check_autoEntry1(string[] sUser, string sKCode, string sBCode) {
            object[] results = this.Invoke("Check_autoEntry1", new object[] {
                        sUser,
                        sKCode,
                        sBCode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheck_autoEntry1(string[] sUser, string sKCode, string sBCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Check_autoEntry1", new object[] {
                        sUser,
                        sKCode,
                        sBCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndCheck_autoEntry1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_Stodokesaki2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_Stodokesaki2(string[] sUser, string sKCode, string sBCode, string sTCode, string sYCode) {
            object[] results = this.Invoke("Get_Stodokesaki2", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sYCode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_Stodokesaki2(string[] sUser, string sKCode, string sBCode, string sTCode, string sYCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_Stodokesaki2", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sTCode,
                        sYCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_Stodokesaki2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_autoEntryPref2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_autoEntryPref2(string[] sUser, string sYCode) {
            object[] results = this.Invoke("Get_autoEntryPref2", new object[] {
                        sUser,
                        sYCode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_autoEntryPref2(string[] sUser, string sYCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_autoEntryPref2", new object[] {
                        sUser,
                        sYCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_autoEntryPref2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_autoEntryClaim2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_autoEntryClaim2(string[] sUser, string sKCode, string sBCode, string sBYCode, string sICode) {
            object[] results = this.Invoke("Get_autoEntryClaim2", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sBYCode,
                        sICode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_autoEntryClaim2(string[] sUser, string sKCode, string sBCode, string sBYCode, string sICode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_autoEntryClaim2", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        sBYCode,
                        sICode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_autoEntryClaim2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_autoEntryPref3", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_autoEntryPref3(string[] sUser, string sKaiinCode, string sBumonCode, string sNiukeCode, string sYuubin, string sJuusyo, string sShimei) {
            object[] results = this.Invoke("Get_autoEntryPref3", new object[] {
                        sUser,
                        sKaiinCode,
                        sBumonCode,
                        sNiukeCode,
                        sYuubin,
                        sJuusyo,
                        sShimei});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_autoEntryPref3(string[] sUser, string sKaiinCode, string sBumonCode, string sNiukeCode, string sYuubin, string sJuusyo, string sShimei, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_autoEntryPref3", new object[] {
                        sUser,
                        sKaiinCode,
                        sBumonCode,
                        sNiukeCode,
                        sYuubin,
                        sJuusyo,
                        sShimei}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_autoEntryPref3(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/wakeupDB", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wakeupDB() {
            object[] results = this.Invoke("wakeupDB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwakeupDB(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wakeupDB", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwakeupDB(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/wakeupDB2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wakeupDB2(int iConCnt) {
            object[] results = this.Invoke("wakeupDB2", new object[] {
                        iConCnt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwakeupDB2(int iConCnt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wakeupDB2", new object[] {
                        iConCnt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwakeupDB2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
