//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.42000 によって自動生成されました。
// 
#pragma warning disable 1591

namespace is2WakeUpDBCon.is2print {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://Walkthrough/XmlWebServices/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Get_InvoicePrintDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_InvoiceNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Set_InvoiceNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ConsignorPrintDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ConsigneePrintDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_NotePrintDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_UnpublishedOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ShippedUnpublishedOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_PublishedPrintDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ConsigneePrintData2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ConsigneePrintData3OperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_PublishedPrintData2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_PublishedPrintData3OperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_PublishedPrintData4OperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_DeliShopOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ShopZipOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ShopTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_PrefDeliShopOperationCompleted;
        
        private System.Threading.SendOrPostCallback wakeupDBOperationCompleted;
        
        private System.Threading.SendOrPostCallback wakeupDB2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://wwwis2.fukutsu.co.jp/is2/is2print/Service1.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Get_InvoicePrintDataCompletedEventHandler Get_InvoicePrintDataCompleted;
        
        /// <remarks/>
        public event Get_InvoiceNoCompletedEventHandler Get_InvoiceNoCompleted;
        
        /// <remarks/>
        public event Set_InvoiceNoCompletedEventHandler Set_InvoiceNoCompleted;
        
        /// <remarks/>
        public event Get_ConsignorPrintDataCompletedEventHandler Get_ConsignorPrintDataCompleted;
        
        /// <remarks/>
        public event Get_ConsigneePrintDataCompletedEventHandler Get_ConsigneePrintDataCompleted;
        
        /// <remarks/>
        public event Get_NotePrintDataCompletedEventHandler Get_NotePrintDataCompleted;
        
        /// <remarks/>
        public event Get_UnpublishedCompletedEventHandler Get_UnpublishedCompleted;
        
        /// <remarks/>
        public event Get_ShippedUnpublishedCompletedEventHandler Get_ShippedUnpublishedCompleted;
        
        /// <remarks/>
        public event Get_PublishedPrintDataCompletedEventHandler Get_PublishedPrintDataCompleted;
        
        /// <remarks/>
        public event Get_ConsigneePrintData2CompletedEventHandler Get_ConsigneePrintData2Completed;
        
        /// <remarks/>
        public event Get_ConsigneePrintData3CompletedEventHandler Get_ConsigneePrintData3Completed;
        
        /// <remarks/>
        public event Get_PublishedPrintData2CompletedEventHandler Get_PublishedPrintData2Completed;
        
        /// <remarks/>
        public event Get_PublishedPrintData3CompletedEventHandler Get_PublishedPrintData3Completed;
        
        /// <remarks/>
        public event Get_PublishedPrintData4CompletedEventHandler Get_PublishedPrintData4Completed;
        
        /// <remarks/>
        public event Get_DeliShopCompletedEventHandler Get_DeliShopCompleted;
        
        /// <remarks/>
        public event Get_ShopZipCompletedEventHandler Get_ShopZipCompleted;
        
        /// <remarks/>
        public event Get_ShopTypeCompletedEventHandler Get_ShopTypeCompleted;
        
        /// <remarks/>
        public event Get_PrefDeliShopCompletedEventHandler Get_PrefDeliShopCompleted;
        
        /// <remarks/>
        public event wakeupDBCompletedEventHandler wakeupDBCompleted;
        
        /// <remarks/>
        public event wakeupDB2CompletedEventHandler wakeupDB2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_InvoicePrintData", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_InvoicePrintData(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_InvoicePrintData", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_InvoicePrintData(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_InvoicePrintData", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_InvoicePrintData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_InvoicePrintDataAsync(string[] sUser, string[] sKey) {
            this.Get_InvoicePrintDataAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_InvoicePrintDataAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_InvoicePrintDataOperationCompleted == null)) {
                this.Get_InvoicePrintDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_InvoicePrintDataOperationCompleted);
            }
            this.InvokeAsync("Get_InvoicePrintData", new object[] {
                        sUser,
                        sKey}, this.Get_InvoicePrintDataOperationCompleted, userState);
        }
        
        private void OnGet_InvoicePrintDataOperationCompleted(object arg) {
            if ((this.Get_InvoicePrintDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_InvoicePrintDataCompleted(this, new Get_InvoicePrintDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_InvoiceNo", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_InvoiceNo(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_InvoiceNo", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_InvoiceNo(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_InvoiceNo", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_InvoiceNo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_InvoiceNoAsync(string[] sUser, string[] sKey) {
            this.Get_InvoiceNoAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_InvoiceNoAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_InvoiceNoOperationCompleted == null)) {
                this.Get_InvoiceNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_InvoiceNoOperationCompleted);
            }
            this.InvokeAsync("Get_InvoiceNo", new object[] {
                        sUser,
                        sKey}, this.Get_InvoiceNoOperationCompleted, userState);
        }
        
        private void OnGet_InvoiceNoOperationCompleted(object arg) {
            if ((this.Get_InvoiceNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_InvoiceNoCompleted(this, new Get_InvoiceNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Set_InvoiceNo", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Set_InvoiceNo(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Set_InvoiceNo", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSet_InvoiceNo(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Set_InvoiceNo", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndSet_InvoiceNo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Set_InvoiceNoAsync(string[] sUser, string[] sKey) {
            this.Set_InvoiceNoAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Set_InvoiceNoAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Set_InvoiceNoOperationCompleted == null)) {
                this.Set_InvoiceNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSet_InvoiceNoOperationCompleted);
            }
            this.InvokeAsync("Set_InvoiceNo", new object[] {
                        sUser,
                        sKey}, this.Set_InvoiceNoOperationCompleted, userState);
        }
        
        private void OnSet_InvoiceNoOperationCompleted(object arg) {
            if ((this.Set_InvoiceNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Set_InvoiceNoCompleted(this, new Set_InvoiceNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_ConsignorPrintData", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_ConsignorPrintData(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_ConsignorPrintData", new object[] {
                        sUser,
                        sKey});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_ConsignorPrintData(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_ConsignorPrintData", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_ConsignorPrintData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_ConsignorPrintDataAsync(string[] sUser, string[] sKey) {
            this.Get_ConsignorPrintDataAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_ConsignorPrintDataAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_ConsignorPrintDataOperationCompleted == null)) {
                this.Get_ConsignorPrintDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ConsignorPrintDataOperationCompleted);
            }
            this.InvokeAsync("Get_ConsignorPrintData", new object[] {
                        sUser,
                        sKey}, this.Get_ConsignorPrintDataOperationCompleted, userState);
        }
        
        private void OnGet_ConsignorPrintDataOperationCompleted(object arg) {
            if ((this.Get_ConsignorPrintDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ConsignorPrintDataCompleted(this, new Get_ConsignorPrintDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_ConsigneePrintData", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_ConsigneePrintData(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_ConsigneePrintData", new object[] {
                        sUser,
                        sKey});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_ConsigneePrintData(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_ConsigneePrintData", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_ConsigneePrintData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_ConsigneePrintDataAsync(string[] sUser, string[] sKey) {
            this.Get_ConsigneePrintDataAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_ConsigneePrintDataAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_ConsigneePrintDataOperationCompleted == null)) {
                this.Get_ConsigneePrintDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ConsigneePrintDataOperationCompleted);
            }
            this.InvokeAsync("Get_ConsigneePrintData", new object[] {
                        sUser,
                        sKey}, this.Get_ConsigneePrintDataOperationCompleted, userState);
        }
        
        private void OnGet_ConsigneePrintDataOperationCompleted(object arg) {
            if ((this.Get_ConsigneePrintDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ConsigneePrintDataCompleted(this, new Get_ConsigneePrintDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_NotePrintData", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_NotePrintData(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_NotePrintData", new object[] {
                        sUser,
                        sKey});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_NotePrintData(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_NotePrintData", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_NotePrintData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_NotePrintDataAsync(string[] sUser, string[] sKey) {
            this.Get_NotePrintDataAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_NotePrintDataAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_NotePrintDataOperationCompleted == null)) {
                this.Get_NotePrintDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_NotePrintDataOperationCompleted);
            }
            this.InvokeAsync("Get_NotePrintData", new object[] {
                        sUser,
                        sKey}, this.Get_NotePrintDataOperationCompleted, userState);
        }
        
        private void OnGet_NotePrintDataOperationCompleted(object arg) {
            if ((this.Get_NotePrintDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_NotePrintDataCompleted(this, new Get_NotePrintDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_Unpublished", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_Unpublished(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_Unpublished", new object[] {
                        sUser,
                        sKey});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_Unpublished(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_Unpublished", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_Unpublished(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_UnpublishedAsync(string[] sUser, string[] sKey) {
            this.Get_UnpublishedAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_UnpublishedAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_UnpublishedOperationCompleted == null)) {
                this.Get_UnpublishedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_UnpublishedOperationCompleted);
            }
            this.InvokeAsync("Get_Unpublished", new object[] {
                        sUser,
                        sKey}, this.Get_UnpublishedOperationCompleted, userState);
        }
        
        private void OnGet_UnpublishedOperationCompleted(object arg) {
            if ((this.Get_UnpublishedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_UnpublishedCompleted(this, new Get_UnpublishedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_ShippedUnpublished", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_ShippedUnpublished(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_ShippedUnpublished", new object[] {
                        sUser,
                        sKey});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_ShippedUnpublished(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_ShippedUnpublished", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_ShippedUnpublished(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_ShippedUnpublishedAsync(string[] sUser, string[] sKey) {
            this.Get_ShippedUnpublishedAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_ShippedUnpublishedAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_ShippedUnpublishedOperationCompleted == null)) {
                this.Get_ShippedUnpublishedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ShippedUnpublishedOperationCompleted);
            }
            this.InvokeAsync("Get_ShippedUnpublished", new object[] {
                        sUser,
                        sKey}, this.Get_ShippedUnpublishedOperationCompleted, userState);
        }
        
        private void OnGet_ShippedUnpublishedOperationCompleted(object arg) {
            if ((this.Get_ShippedUnpublishedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ShippedUnpublishedCompleted(this, new Get_ShippedUnpublishedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_PublishedPrintData", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_PublishedPrintData(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday) {
            object[] results = this.Invoke("Get_PublishedPrintData", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        iSyuka,
                        sSday,
                        sEday});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_PublishedPrintData(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_PublishedPrintData", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        iSyuka,
                        sSday,
                        sEday}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_PublishedPrintData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_PublishedPrintDataAsync(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday) {
            this.Get_PublishedPrintDataAsync(sUser, sKCode, sBCode, iSyuka, sSday, sEday, null);
        }
        
        /// <remarks/>
        public void Get_PublishedPrintDataAsync(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, object userState) {
            if ((this.Get_PublishedPrintDataOperationCompleted == null)) {
                this.Get_PublishedPrintDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_PublishedPrintDataOperationCompleted);
            }
            this.InvokeAsync("Get_PublishedPrintData", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        iSyuka,
                        sSday,
                        sEday}, this.Get_PublishedPrintDataOperationCompleted, userState);
        }
        
        private void OnGet_PublishedPrintDataOperationCompleted(object arg) {
            if ((this.Get_PublishedPrintDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_PublishedPrintDataCompleted(this, new Get_PublishedPrintDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_ConsigneePrintData2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_ConsigneePrintData2(string[] sUser, string[] sKey, string sKana, string sTCode, string sTelNo, string sTelNo2, string sTelNo3, string sName, int iSortLabel1, int iSortPat1, int iSortLabel2, int iSortPat2) {
            object[] results = this.Invoke("Get_ConsigneePrintData2", new object[] {
                        sUser,
                        sKey,
                        sKana,
                        sTCode,
                        sTelNo,
                        sTelNo2,
                        sTelNo3,
                        sName,
                        iSortLabel1,
                        iSortPat1,
                        iSortLabel2,
                        iSortPat2});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_ConsigneePrintData2(string[] sUser, string[] sKey, string sKana, string sTCode, string sTelNo, string sTelNo2, string sTelNo3, string sName, int iSortLabel1, int iSortPat1, int iSortLabel2, int iSortPat2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_ConsigneePrintData2", new object[] {
                        sUser,
                        sKey,
                        sKana,
                        sTCode,
                        sTelNo,
                        sTelNo2,
                        sTelNo3,
                        sName,
                        iSortLabel1,
                        iSortPat1,
                        iSortLabel2,
                        iSortPat2}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_ConsigneePrintData2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_ConsigneePrintData2Async(string[] sUser, string[] sKey, string sKana, string sTCode, string sTelNo, string sTelNo2, string sTelNo3, string sName, int iSortLabel1, int iSortPat1, int iSortLabel2, int iSortPat2) {
            this.Get_ConsigneePrintData2Async(sUser, sKey, sKana, sTCode, sTelNo, sTelNo2, sTelNo3, sName, iSortLabel1, iSortPat1, iSortLabel2, iSortPat2, null);
        }
        
        /// <remarks/>
        public void Get_ConsigneePrintData2Async(string[] sUser, string[] sKey, string sKana, string sTCode, string sTelNo, string sTelNo2, string sTelNo3, string sName, int iSortLabel1, int iSortPat1, int iSortLabel2, int iSortPat2, object userState) {
            if ((this.Get_ConsigneePrintData2OperationCompleted == null)) {
                this.Get_ConsigneePrintData2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ConsigneePrintData2OperationCompleted);
            }
            this.InvokeAsync("Get_ConsigneePrintData2", new object[] {
                        sUser,
                        sKey,
                        sKana,
                        sTCode,
                        sTelNo,
                        sTelNo2,
                        sTelNo3,
                        sName,
                        iSortLabel1,
                        iSortPat1,
                        iSortLabel2,
                        iSortPat2}, this.Get_ConsigneePrintData2OperationCompleted, userState);
        }
        
        private void OnGet_ConsigneePrintData2OperationCompleted(object arg) {
            if ((this.Get_ConsigneePrintData2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ConsigneePrintData2Completed(this, new Get_ConsigneePrintData2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_ConsigneePrintData3", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_ConsigneePrintData3(string[] sUser, string[] sKey, string sKana, string sTCode, string sTelNo, string sTelNo2, string sTelNo3, string sName, int iSortLabel1, int iSortPat1, int iSortLabel2, int iSortPat2, string sUpdateDay) {
            object[] results = this.Invoke("Get_ConsigneePrintData3", new object[] {
                        sUser,
                        sKey,
                        sKana,
                        sTCode,
                        sTelNo,
                        sTelNo2,
                        sTelNo3,
                        sName,
                        iSortLabel1,
                        iSortPat1,
                        iSortLabel2,
                        iSortPat2,
                        sUpdateDay});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_ConsigneePrintData3(string[] sUser, string[] sKey, string sKana, string sTCode, string sTelNo, string sTelNo2, string sTelNo3, string sName, int iSortLabel1, int iSortPat1, int iSortLabel2, int iSortPat2, string sUpdateDay, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_ConsigneePrintData3", new object[] {
                        sUser,
                        sKey,
                        sKana,
                        sTCode,
                        sTelNo,
                        sTelNo2,
                        sTelNo3,
                        sName,
                        iSortLabel1,
                        iSortPat1,
                        iSortLabel2,
                        iSortPat2,
                        sUpdateDay}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_ConsigneePrintData3(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_ConsigneePrintData3Async(string[] sUser, string[] sKey, string sKana, string sTCode, string sTelNo, string sTelNo2, string sTelNo3, string sName, int iSortLabel1, int iSortPat1, int iSortLabel2, int iSortPat2, string sUpdateDay) {
            this.Get_ConsigneePrintData3Async(sUser, sKey, sKana, sTCode, sTelNo, sTelNo2, sTelNo3, sName, iSortLabel1, iSortPat1, iSortLabel2, iSortPat2, sUpdateDay, null);
        }
        
        /// <remarks/>
        public void Get_ConsigneePrintData3Async(string[] sUser, string[] sKey, string sKana, string sTCode, string sTelNo, string sTelNo2, string sTelNo3, string sName, int iSortLabel1, int iSortPat1, int iSortLabel2, int iSortPat2, string sUpdateDay, object userState) {
            if ((this.Get_ConsigneePrintData3OperationCompleted == null)) {
                this.Get_ConsigneePrintData3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ConsigneePrintData3OperationCompleted);
            }
            this.InvokeAsync("Get_ConsigneePrintData3", new object[] {
                        sUser,
                        sKey,
                        sKana,
                        sTCode,
                        sTelNo,
                        sTelNo2,
                        sTelNo3,
                        sName,
                        iSortLabel1,
                        iSortPat1,
                        iSortLabel2,
                        iSortPat2,
                        sUpdateDay}, this.Get_ConsigneePrintData3OperationCompleted, userState);
        }
        
        private void OnGet_ConsigneePrintData3OperationCompleted(object arg) {
            if ((this.Get_ConsigneePrintData3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ConsigneePrintData3Completed(this, new Get_ConsigneePrintData3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_PublishedPrintData2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_PublishedPrintData2(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, string sIraiCd) {
            object[] results = this.Invoke("Get_PublishedPrintData2", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        iSyuka,
                        sSday,
                        sEday,
                        sIraiCd});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_PublishedPrintData2(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, string sIraiCd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_PublishedPrintData2", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        iSyuka,
                        sSday,
                        sEday,
                        sIraiCd}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_PublishedPrintData2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_PublishedPrintData2Async(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, string sIraiCd) {
            this.Get_PublishedPrintData2Async(sUser, sKCode, sBCode, iSyuka, sSday, sEday, sIraiCd, null);
        }
        
        /// <remarks/>
        public void Get_PublishedPrintData2Async(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, string sIraiCd, object userState) {
            if ((this.Get_PublishedPrintData2OperationCompleted == null)) {
                this.Get_PublishedPrintData2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_PublishedPrintData2OperationCompleted);
            }
            this.InvokeAsync("Get_PublishedPrintData2", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        iSyuka,
                        sSday,
                        sEday,
                        sIraiCd}, this.Get_PublishedPrintData2OperationCompleted, userState);
        }
        
        private void OnGet_PublishedPrintData2OperationCompleted(object arg) {
            if ((this.Get_PublishedPrintData2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_PublishedPrintData2Completed(this, new Get_PublishedPrintData2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_PublishedPrintData3", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_PublishedPrintData3(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, string sIraiCd, string sJyoutai) {
            object[] results = this.Invoke("Get_PublishedPrintData3", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        iSyuka,
                        sSday,
                        sEday,
                        sIraiCd,
                        sJyoutai});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_PublishedPrintData3(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, string sIraiCd, string sJyoutai, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_PublishedPrintData3", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        iSyuka,
                        sSday,
                        sEday,
                        sIraiCd,
                        sJyoutai}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_PublishedPrintData3(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_PublishedPrintData3Async(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, string sIraiCd, string sJyoutai) {
            this.Get_PublishedPrintData3Async(sUser, sKCode, sBCode, iSyuka, sSday, sEday, sIraiCd, sJyoutai, null);
        }
        
        /// <remarks/>
        public void Get_PublishedPrintData3Async(string[] sUser, string sKCode, string sBCode, int iSyuka, string sSday, string sEday, string sIraiCd, string sJyoutai, object userState) {
            if ((this.Get_PublishedPrintData3OperationCompleted == null)) {
                this.Get_PublishedPrintData3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_PublishedPrintData3OperationCompleted);
            }
            this.InvokeAsync("Get_PublishedPrintData3", new object[] {
                        sUser,
                        sKCode,
                        sBCode,
                        iSyuka,
                        sSday,
                        sEday,
                        sIraiCd,
                        sJyoutai}, this.Get_PublishedPrintData3OperationCompleted, userState);
        }
        
        private void OnGet_PublishedPrintData3OperationCompleted(object arg) {
            if ((this.Get_PublishedPrintData3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_PublishedPrintData3Completed(this, new Get_PublishedPrintData3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_PublishedPrintData4", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Get_PublishedPrintData4(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_PublishedPrintData4", new object[] {
                        sUser,
                        sKey});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_PublishedPrintData4(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_PublishedPrintData4", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndGet_PublishedPrintData4(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_PublishedPrintData4Async(string[] sUser, string[] sKey) {
            this.Get_PublishedPrintData4Async(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_PublishedPrintData4Async(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_PublishedPrintData4OperationCompleted == null)) {
                this.Get_PublishedPrintData4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_PublishedPrintData4OperationCompleted);
            }
            this.InvokeAsync("Get_PublishedPrintData4", new object[] {
                        sUser,
                        sKey}, this.Get_PublishedPrintData4OperationCompleted, userState);
        }
        
        private void OnGet_PublishedPrintData4OperationCompleted(object arg) {
            if ((this.Get_PublishedPrintData4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_PublishedPrintData4Completed(this, new Get_PublishedPrintData4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_DeliShop", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_DeliShop(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_DeliShop", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_DeliShop(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_DeliShop", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_DeliShop(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_DeliShopAsync(string[] sUser, string[] sKey) {
            this.Get_DeliShopAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_DeliShopAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_DeliShopOperationCompleted == null)) {
                this.Get_DeliShopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_DeliShopOperationCompleted);
            }
            this.InvokeAsync("Get_DeliShop", new object[] {
                        sUser,
                        sKey}, this.Get_DeliShopOperationCompleted, userState);
        }
        
        private void OnGet_DeliShopOperationCompleted(object arg) {
            if ((this.Get_DeliShopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_DeliShopCompleted(this, new Get_DeliShopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_ShopZip", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_ShopZip(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_ShopZip", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_ShopZip(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_ShopZip", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_ShopZip(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_ShopZipAsync(string[] sUser, string[] sKey) {
            this.Get_ShopZipAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_ShopZipAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_ShopZipOperationCompleted == null)) {
                this.Get_ShopZipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ShopZipOperationCompleted);
            }
            this.InvokeAsync("Get_ShopZip", new object[] {
                        sUser,
                        sKey}, this.Get_ShopZipOperationCompleted, userState);
        }
        
        private void OnGet_ShopZipOperationCompleted(object arg) {
            if ((this.Get_ShopZipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ShopZipCompleted(this, new Get_ShopZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_ShopType", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_ShopType(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_ShopType", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_ShopType(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_ShopType", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_ShopType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_ShopTypeAsync(string[] sUser, string[] sKey) {
            this.Get_ShopTypeAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_ShopTypeAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_ShopTypeOperationCompleted == null)) {
                this.Get_ShopTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ShopTypeOperationCompleted);
            }
            this.InvokeAsync("Get_ShopType", new object[] {
                        sUser,
                        sKey}, this.Get_ShopTypeOperationCompleted, userState);
        }
        
        private void OnGet_ShopTypeOperationCompleted(object arg) {
            if ((this.Get_ShopTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ShopTypeCompleted(this, new Get_ShopTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/Get_PrefDeliShop", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Get_PrefDeliShop(string[] sUser, string[] sKey) {
            object[] results = this.Invoke("Get_PrefDeliShop", new object[] {
                        sUser,
                        sKey});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGet_PrefDeliShop(string[] sUser, string[] sKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Get_PrefDeliShop", new object[] {
                        sUser,
                        sKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGet_PrefDeliShop(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_PrefDeliShopAsync(string[] sUser, string[] sKey) {
            this.Get_PrefDeliShopAsync(sUser, sKey, null);
        }
        
        /// <remarks/>
        public void Get_PrefDeliShopAsync(string[] sUser, string[] sKey, object userState) {
            if ((this.Get_PrefDeliShopOperationCompleted == null)) {
                this.Get_PrefDeliShopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_PrefDeliShopOperationCompleted);
            }
            this.InvokeAsync("Get_PrefDeliShop", new object[] {
                        sUser,
                        sKey}, this.Get_PrefDeliShopOperationCompleted, userState);
        }
        
        private void OnGet_PrefDeliShopOperationCompleted(object arg) {
            if ((this.Get_PrefDeliShopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_PrefDeliShopCompleted(this, new Get_PrefDeliShopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/wakeupDB", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wakeupDB() {
            object[] results = this.Invoke("wakeupDB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwakeupDB(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wakeupDB", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwakeupDB(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wakeupDBAsync() {
            this.wakeupDBAsync(null);
        }
        
        /// <remarks/>
        public void wakeupDBAsync(object userState) {
            if ((this.wakeupDBOperationCompleted == null)) {
                this.wakeupDBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwakeupDBOperationCompleted);
            }
            this.InvokeAsync("wakeupDB", new object[0], this.wakeupDBOperationCompleted, userState);
        }
        
        private void OnwakeupDBOperationCompleted(object arg) {
            if ((this.wakeupDBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wakeupDBCompleted(this, new wakeupDBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Walkthrough/XmlWebServices/wakeupDB2", RequestNamespace="http://Walkthrough/XmlWebServices/", ResponseNamespace="http://Walkthrough/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string wakeupDB2(int iConCnt) {
            object[] results = this.Invoke("wakeupDB2", new object[] {
                        iConCnt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginwakeupDB2(int iConCnt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("wakeupDB2", new object[] {
                        iConCnt}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndwakeupDB2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wakeupDB2Async(int iConCnt) {
            this.wakeupDB2Async(iConCnt, null);
        }
        
        /// <remarks/>
        public void wakeupDB2Async(int iConCnt, object userState) {
            if ((this.wakeupDB2OperationCompleted == null)) {
                this.wakeupDB2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnwakeupDB2OperationCompleted);
            }
            this.InvokeAsync("wakeupDB2", new object[] {
                        iConCnt}, this.wakeupDB2OperationCompleted, userState);
        }
        
        private void OnwakeupDB2OperationCompleted(object arg) {
            if ((this.wakeupDB2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wakeupDB2Completed(this, new wakeupDB2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_InvoicePrintDataCompletedEventHandler(object sender, Get_InvoicePrintDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_InvoicePrintDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_InvoicePrintDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_InvoiceNoCompletedEventHandler(object sender, Get_InvoiceNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_InvoiceNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_InvoiceNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Set_InvoiceNoCompletedEventHandler(object sender, Set_InvoiceNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Set_InvoiceNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Set_InvoiceNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_ConsignorPrintDataCompletedEventHandler(object sender, Get_ConsignorPrintDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ConsignorPrintDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ConsignorPrintDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_ConsigneePrintDataCompletedEventHandler(object sender, Get_ConsigneePrintDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ConsigneePrintDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ConsigneePrintDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_NotePrintDataCompletedEventHandler(object sender, Get_NotePrintDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_NotePrintDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_NotePrintDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_UnpublishedCompletedEventHandler(object sender, Get_UnpublishedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_UnpublishedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_UnpublishedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_ShippedUnpublishedCompletedEventHandler(object sender, Get_ShippedUnpublishedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ShippedUnpublishedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ShippedUnpublishedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_PublishedPrintDataCompletedEventHandler(object sender, Get_PublishedPrintDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_PublishedPrintDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_PublishedPrintDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_ConsigneePrintData2CompletedEventHandler(object sender, Get_ConsigneePrintData2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ConsigneePrintData2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ConsigneePrintData2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_ConsigneePrintData3CompletedEventHandler(object sender, Get_ConsigneePrintData3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ConsigneePrintData3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ConsigneePrintData3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_PublishedPrintData2CompletedEventHandler(object sender, Get_PublishedPrintData2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_PublishedPrintData2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_PublishedPrintData2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_PublishedPrintData3CompletedEventHandler(object sender, Get_PublishedPrintData3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_PublishedPrintData3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_PublishedPrintData3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_PublishedPrintData4CompletedEventHandler(object sender, Get_PublishedPrintData4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_PublishedPrintData4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_PublishedPrintData4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_DeliShopCompletedEventHandler(object sender, Get_DeliShopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_DeliShopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_DeliShopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_ShopZipCompletedEventHandler(object sender, Get_ShopZipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ShopZipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ShopZipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_ShopTypeCompletedEventHandler(object sender, Get_ShopTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ShopTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ShopTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void Get_PrefDeliShopCompletedEventHandler(object sender, Get_PrefDeliShopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_PrefDeliShopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_PrefDeliShopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void wakeupDBCompletedEventHandler(object sender, wakeupDBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wakeupDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wakeupDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void wakeupDB2CompletedEventHandler(object sender, wakeupDB2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wakeupDB2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wakeupDB2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591